services:
  back-end:
    build:
      context: ./back-end  # Chemin vers le dossier back-end
      dockerfile: Dockerfile  # Nom du Dockerfile
    image: softy-pinko-back-end:task5  # Nom de l'image
    ports:
      - "5252"  # Mappage ports (host:container)

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    ports:
      - "9000"
    depends_on:  # Dépendance (le back-end démarre en premier)
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"  # Seul le proxy est accessible depuis l'extérieur
    depends_on:
      - front-end
      - back-end